app:
    resource: '@AppBundle/Controller/'
    type: annotation

user_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /user

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /

fos_user_login:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_registation:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_reetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /user/profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /user/profile